
# zf210607.1715
# sources: 
# https://esphome.io/components/sensor/dallas.html

esphome:
  name: 1w_th_solar
  platform: ESP8266
  board: nodemcuv2

# Configuration WIFI
wifi:
  networks:
  - ssid: !secret wifi_ssid
  - password: !secret wifi_password
  - ssid: !secret wifi_ssid2
  - password: !secret wifi_password2
  - ssid: !secret wifi_ssid3
  - password: !secret wifi_password3
  - ssid: !secret wifi_ssid4
  - password: !secret wifi_password4
  - ssid: !secret wifi_ssid5
  - password: !secret wifi_password5
  - ssid: !secret wifi_ssid6
  - password: !secret wifi_password6

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "1w_th_solar Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80

# Définition des Switch's
switch:
  - platform: gpio
    name: "1w_th_solar LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "1w_th_solar Restart"

# Définition du bouton physique
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "1w_th_solar button"
    on_press:
      - switch.toggle: led


# Définitions des texts sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: 1w_th_solar IP Address
      id: wifi_ip
    ssid:
      name: 1w_th_solar Connected SSID
      id: wifi_ssid



# Example configuration entry
dallas:
  - pin: D2
    update_interval: 10s




# Sensors
sensor:

######### juste là pour changer l'harmonique du CPU qui interagit avec le WIFI sur mes NodeMCU lowcost :-(
#   - platform: homeassistant
#     name: "th8 Temp"
#     entity_id: sensor.th8_temperature
# #    id: th8_th
#     internal: true
#########

  - platform: wifi_signal
    name: "1w_th_solar Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "1w_th_solar uptime"
    update_interval: 60s


  - platform: dallas
    address: 0x7E0300A279AFA028
    name: "1w_th_solar aller"

  - platform: dallas
    address: 0x860301A279FFE428
    name: "1w_th_solar retour"

  - platform: dallas
    address: 0x710301A279230C28
    name: "1w_th_solar boiler2"

  - platform: dallas
    address: 0xD80301A279E37228
    name: "1w_th_solar boiler1"

  - platform: dallas
    address: 0xCC0301A2793FD328
    name: "1w_th_solar consigne"

  - platform: dallas
    address: 0xEE0301A27920E728
    name: "1w_th_solar froid"

  - platform: dallas
    address: 0xA40301A279F37228
    name: "1w_th_solar ext sud"


