#------------------------------
#-- batmon_d1_1.yaml
#-- Petit code pour monitorer une batterie
#-- Lit le port ADC0 et l'envoie sur un mqtt broker
#-- Si la pin D2 est à GND, alors part en dsleep pour une certaine durée
#-- location: xxx
#-- zf221007.2221
#--
# sources: 
# ...

esphome:
  name: batmon_d1_1
  on_boot:
  - switch.turn_on: led

esp8266:
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_3G_zf2
  password: !secret wifi_pass_3G_zf2

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32-ble-hub1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
  level: DEBUG
  logs:
    logger: INFO
    adc: INFO
    captive_portal: INFO
    deep_sleep: INFO
    htu21d: INFO
    i2c: INFO
    ota: INFO
    restart: INFO
    sensor: INFO
    switch: INFO
    switch.gpio: INFO
    uptime.sensor: INFO
    web_server: INFO
    wifi_signal.sensor: INFO
    mqtt: INFO
    mqtt.component: INFO
    mqtt.client: INFO
    mqtt.switch: INFO
    mqtt.sensor: INFO


# Enable Home Assistant API
#api:
#  password: !secret api_password

ota:
  password: !secret ota_password


# Définition des Switch's
switch:
  - platform: gpio
    name: "batmon_d1_1 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "batmon_d1_1 Restart"

# WEB Server
web_server:
  port: 80


# MQTT server
mqtt:
  broker:  !secret mqtt_server_dev
  port:  !secret mqtt_port_dev
  username:  !secret mqtt_user_dev
  password:  !secret mqtt_password_dev


# Sensors
sensor:
  - platform: wifi_signal
    name: "batmon_d1_1 Signal Wi-Fi"
    update_interval: 60s
    on_value:
      if:
        condition:
          mqtt.connected:
        then:
          - logger.log: Je suis connected sur le mqtt et j'envoie la sauce !
          - if:
              condition:
                lambda: 'return id(batmon_d1_1_sleep_mode).state == 1;'
              then:
                - delay: 1s
                - logger.log: On me demande de dormir !
                - deep_sleep.enter: deep_sleep_1
        else:
          - logger.log: Erreur 007 *********************************************************
          - deep_sleep.enter: deep_sleep_1

  - platform: uptime
    name: "batmon_d1_1 uptime"
    update_interval: 60s

# valeur brute en volts de l'ADC
  - platform: adc
    pin: VCC
    name: "batmon_d1_1 brut en volts"
    id: batmon_d1_1_brut_en_volts
    update_interval: 2s
    unit_of_measurement: "V"


# Définition des binary sensor
binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    name: "batmon_d1_1 sleep mode"
    id: batmon_d1_1_sleep_mode


# Sensors text
text_sensor:
  - platform: version
    name: "batmon_d1_1 Version 1150"

  - platform: wifi_info
    ip_address:
      name: batmon_d1_1 IP Address
      id: wifi_ip
    ssid:
      name: batmon_d1_1 Connected SSID
      id: wifi_ssid


# Deep Sleep
deep_sleep:
#  run_duration: 20s
  sleep_duration: 10s
  id: deep_sleep_1
