#------------------------------
#-- boiler_pwm1.yaml
#-- Petit code pour faire un PWM pour piloter le chauffe eau à base d'esp mini d1
#-- blablabla
#-- location: buanderie
#-- zf221120.1444
#--
# sources: 
# ...

esphome:
  name: boiler_pwm1

esp8266:
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu6
  password: !secret wifi_pass_apzuzu6

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "boiler_pwm1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


# Configuration 1-wire pour les capteurs de température DS18B20
dallas:
  - pin: D5
    update_interval: 15s


# Définition des Switch's
switch:
  - platform: gpio
    name: "boiler_pwm1 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "boiler_pwm1 Restart"


# Définition des Sensors
sensor:
  - platform: wifi_signal
    name: "boiler_pwm1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "boiler_pwm1 uptime"
    update_interval: 15s

# Température variateur
  - platform: dallas
    address: 0x1a0301a279494a28
    name: "boiler_pwm1 temp"
    id: boiler_pwm1_temp
    # filters:
    #     - lambda: return ( x - (id(th_ext_sud_temperature_calibration).state /1) );


# Définition des Sensors text
text_sensor:
  - platform: version
    name: "boiler_pwm1 Version 1221"

  - platform: wifi_info
    ip_address:
      name: boiler_pwm1 IP Address
      id: wifi_ip
    ssid:
      name: boiler_pwm1 Connected SSID
      id: wifi_ssid


# Définition des outputs 
output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: boiler_pwm1_pwm_output


# Définition des lights 
light:
  - platform: monochromatic
    output: boiler_pwm1_pwm_output
    name: boiler_pwm1_pwm_output_power_set"

    