#------------------------------
#-- co2_72.yaml
#-- Petit code mini minilste pour mesurer le COV et eCO2
#-- Lit COV et eCO2 du capteur ccs811
#-- location: chambre à Chloé carton vers mur
#-- zf210720.1033
#--


# sources: 
# https://esphome.io/components/sensor/ccs811.html

esphome:
  name: co2_72
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  
    - ssid: !secret wifi_ssid_apzuzu7
    - password: !secret wifi_pass_apzuzu7

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "co2_72 Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Switch
switch:
  - platform: gpio
    name: "co2_72 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "co2_72 Restart"

# Définition du bouton physique
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "co2_72 button"
    on_press:
      - switch.toggle: led

# WEB Server
web_server:
  port: 80

# MQTT server
mqtt:
  broker:  !secret mqtt_server_dev
  port:  !secret mqtt_port_dev
  username:  !secret mqtt_user_dev
  password:  !secret mqtt_password_dev


# # Définitions des texts sensors
# text_sensor:
#   - platform: wifi_info
#     ip_address:
#       name: 1w_th_solar IP Address
#       id: wifi_ip
#     ssid:
#       name: 1w_th_solar Connected SSID
#       id: wifi_ssid


# I2C conf
i2c:
    sda: D5
    scl: D6
    scan: True

# Sensors
sensor:
  - platform: wifi_signal
    name: "co2_72 Signal Wi-Fi"
    update_interval: 61s

  - platform: uptime
    name: "co2_72 uptime"
    update_interval: 63s

######### juste là pour changer l'harmonique du CPU qui interagit avec le WIFI sur mes NodeMCU lowcost :-(
  - platform: homeassistant
    name: "th8 Temp"
    entity_id: sensor.th8_temperature
    id: th8_th
    internal: true
#   - platform: homeassistant
#     name: "th8 Humi"
#     entity_id: sensor.th8_humidite
#     id: th8_hu
#     internal: true
#   - platform: homeassistant
#     name: "th0 Temp"
#     entity_id: sensor.th0_temperature
#     id: th0_th
#     internal: true
#   - platform: homeassistant
#     name: "th0 Humi"
#     entity_id: sensor.th0_humidite
#     id: th0_hu
#     internal: true
#########


  - platform: ccs811
    baseline: 0xD7BF
#    temperature: th8_th
#    humidity: th8_hu
    update_interval: 15s
    eco2:
      name: "co2_72 eCO2"
    tvoc:
      name: "co2_72 TVOC"


