#------------------------------
#-- co2_66.yaml
#-- Petit code mini minilste pour mesurer le TVOC et eCO2
#-- Lit TVOC et eCO2 du capteur ccs811
#-- location: chambre des parents petit meuble à droite en entrant
#-- zf210720.1026
#--


# sources: 
# https://esphome.io/components/sensor/ccs811.html

esphome:
  name: co2_66
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "co2_66 Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Switch
switch:
  - platform: gpio
    name: "co2_66 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "co2_66 Restart"

# Définition du bouton physique
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "co2_66 button"
    on_press:
      - switch.toggle: led

# WEB Server
web_server:
  port: 80

# MQTT server
mqtt:
  broker:  !secret mqtt_server_dev
  port:  !secret mqtt_port_dev
  username:  !secret mqtt_user_dev
  password:  !secret mqtt_password_dev

# Définitions des texts sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: 1w_th_solar IP Address
      id: wifi_ip
    ssid:
      name: 1w_th_solar Connected SSID
      id: wifi_ssid



# I2C conf
i2c:
    sda: D5
    scl: D6
    scan: True

# Sensors
sensor:
  - platform: wifi_signal
    name: "co2_66 Signal Wi-Fi"
    update_interval: 61s

  - platform: uptime
    name: "co2_66 uptime"
    update_interval: 63s

######### juste là pour changer l'harmonique du CPU qui interagit avec le WIFI sur mes NodeMCU lowcost :-(
  - platform: homeassistant
    name: "th8 Temp"
    entity_id: sensor.th8_temperature
#    id: th8_th
    internal: true
#########

#   - platform: homeassistant
#     name: "th8 Humi"
#     entity_id: sensor.th8_humidite
#     id: th8_hu

  - platform: ccs811
    baseline: 0xC9BE
#    temperature: th8_th
#    humidity: th8_hu
    update_interval: 15s
    eco2:
      name: "co2_66 eCO2"
    tvoc:
      name: "co2_66 TVOC"


