#------------------------------
#-- co2_66.yaml
#-- Petit code mini pour mesurer le COV et eCO2
#-- Lit COV et eCO2 du capteur ccs811
#-- Mesure la concentration d'eCO2  (équivalent calculé en dioxyde de carbone)
#-- dans une plage de 400 à 8 192 parties par million (ppm) et la concentration de COVT
#-- (composé organique volatil total) dans une plage de 0 à 1 187 parties par milliard (ppb). 
#-- Il peut détecter les alcools, les aldéhydes, les cétones, 
#-- les acides organiques, les amines, les hydrocarbures aliphatiques et aromatiques.
#--
#-- location: chambre parents à coté table de nuit zf
#-- zf210720.1033, zf230219.2331, zf240313.1024
#--

# sources: 
# https://esphome.io/components/sensor/ccs811.html
# https://www.adafruit.com/product/3566




esphome:
  name: co2_66

esp8266:
  board: nodemcuv2

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "co2_66 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
#  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


# I2C conf
i2c:
  scl: D1
  sda: D2
  scan: True


# Définition des Switch's
switch:
  - platform: gpio
    name: "co2_66 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "co2_66 Restart"


# Définition des Sensors
sensor:
  - platform: wifi_signal
    name: "co2_66 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "co2_66 uptime"
    update_interval: 60s

  - platform: htu21d
    address: 0x40
    temperature:
      name: "co2_66 Température"
      id: co2_66_temperature
      filters:
        - lambda: return x - 1.6;
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    humidity:
      name: "co2_66 Humidité"
      id: co2_66_humidite
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    update_interval: 5s

  - platform: ccs811
    address: 0x5A
    # baseline: 0x5BB8
    temperature: co2_66_temperature
    humidity: co2_66_humidite
    update_interval: 5s
    eco2:
      name: "co2_66 eCO2"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    tvoc:
      name: "co2_66 TVOC"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5



# Définition des Sensors text
text_sensor:
  - platform: version
    name: "co2_66 Version 1312"

  - platform: wifi_info
    ip_address:
      name: co2_66 IP Address
      id: wifi_ip
    ssid:
      name: co2_66 Connected SSID
      id: wifi_ssid


