#------------------------------
#-- co2_72.yaml
#-- Petit code mini minimaliste pour mesurer le COV et eCO2
#-- Lit COV et eCO2 du capteur ccs811
#-- location: chambre à Chloé carton vers mur
#-- zf210720.1033, zf221209.1348
#--


# sources: 
# https://esphome.io/components/sensor/ccs811.html


esphome:
  name: co2_72

esp8266:
  board: nodemcuv2

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "co2_72 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


# I2C conf
i2c:
    scl: D1
    sda: D2
    scan: True


# Définition des Switch's
switch:
  - platform: gpio
    name: "co2_72 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "co2_72 Restart"


# Définition des Sensors
sensor:
  - platform: wifi_signal
    name: "co2_72 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "co2_72 uptime"
    update_interval: 60s



  - platform: homeassistant
    name: "co2_72 th0 Temp"
    entity_id: sensor.th0_temperature
    id: co2_72_th0_th
    internal: false
  - platform: homeassistant
    name: "co2_72 th0 Humi"
    entity_id: sensor.th0_humidite
    id: co2_72_th0_hu
    internal: false




  - platform: ccs811
    # baseline: 0x5BB8
    temperature: co2_72_th0_th
    humidity: co2_72_th0_hu
    update_interval: 5s
    eco2:
      name: "co2_72 eCO2"
    tvoc:
      name: "co2_72 TVOC"




# Définition des Sensors text
text_sensor:
  - platform: version
    name: "co2_72 Version 1312"

  - platform: wifi_info
    ip_address:
      name: co2_72 IP Address
      id: wifi_ip
    ssid:
      name: co2_72 Connected SSID
      id: wifi_ssid


