#------------------------------
#-- demo-darby1.yaml
#-- Petit code une démo de ESPhome à Darby
#-- allume juste la petite LED
#-- 
#-- zf2205.1220
#--




esphome:
  name: demo-darby1

esp8266:
  board: esp01_1m


# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32-ble-hub1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password




# Définition des Switch's
switch:
  - platform: gpio
    name: "demo-darby1 LED"
    inverted: True
    id: led
    pin: GPIO2
  - platform: restart
    name: "demo-darby1 Restart"


# WEB Server
web_server:
  port: 80


# Sensors
sensor:
  - platform: wifi_signal
    name: "demo-darby1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "demo-darby1 uptime"
    update_interval: 60s


# Sensors text
text_sensor:
  - platform: version
    name: "demo-darby1 Version"

  - platform: wifi_info
    ip_address:
      name: demo-darby1 IP Address
      id: wifi_ip
    ssid:
      name: demo-darby1 Connected SSID
      id: wifi_ssid

