#zf210302.2341

esphome:
  name: dsleep_8285_2
  platform: ESP8266
  board: esp8285
  on_boot:
  - switch.turn_on: led


# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "dsleep_8285_2 Fallback"
    password: !secret ap_wifi_password


captive_portal:

# Enable logging
logger:
  level: DEBUG
  logs:
    logger: INFO
    adc: INFO
    captive_portal: INFO
    deep_sleep: INFO
    htu21d: INFO
    i2c: INFO
    ota: INFO
    restart: INFO
    sensor: INFO
    switch: INFO
    switch.gpio: INFO
    uptime.sensor: INFO
    web_server: INFO
    wifi_signal.sensor: INFO
    mqtt: INFO
    mqtt.component: INFO
    mqtt.client: INFO
    mqtt.switch: INFO
    mqtt.sensor: INFO
    

    
    

# Enable Home Assistant API
#api:
#  password: !secret api_password


ota:
  password: !secret ota_password

# Définition des Switch's
switch:
  - platform: gpio
    name: "dsleep_8285_2 LED"
    inverted: True
    id: led
    pin: GPIO2
  - platform: restart
    name: "dsleep_8285_2 Restart"

# WEB Server
web_server:
  port: 80

# MQTT server
mqtt:
  broker:  !secret mqtt_server_dev
  port:  !secret mqtt_port_dev
  username:  !secret mqtt_user_dev
  password:  !secret mqtt_password_dev



# I2C conf
i2c:
  sda: GPIO4
  scl: GPIO14

# Sensors
sensor:
  - platform: wifi_signal
    name: "dsleep_8285_2 Signal Wi-Fi"
    on_value:
      if:
        condition:
          mqtt.connected:
        then:
#            - delay: 2s
          - logger.log: Je suis connected et envoie la sauce !
          - delay: 1s
          - logger.log: Je vais dormir !
          - deep_sleep.enter: deep_sleep_1
        else:
          - logger.log: WiFi not Antoine connected!
    update_interval: 3s
  - platform: uptime
    name: "dsleep_8285_2 uptime"
    update_interval: 3s
  - platform: htu21d
    temperature:
      name: "dsleep_8285_2 Température"
    humidity:
      name: "dsleep_8285_2 Humidité"
    update_interval: 3s
  - platform: adc
    pin: VCC
    name: "dsleep_8285_2 VCC Voltage"
    update_interval: 3s

# Deep Sleep
deep_sleep:
  run_duration: 10s
  sleep_duration: 10s
  id: deep_sleep_1
  
  


