#zf210302.2202

esphome:
  name: dsleep_mini_d1_1
  platform: ESP8266
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

      
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "dsleep_mini_d1_1 Fallback AP"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#  level: VERBOSE
#  logs:
#    mqtt.component: DEBUG
#    mqtt.client: ERROR

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Définition des Switch's
switch:
  - platform: gpio
    name: "dsleep_mini_d1_1 LED"
    inverted: True
    id: led
    pin: GPIO2
  - platform: restart
    name: "dsleep_mini_d1_1 Restart"

# WEB Server
web_server:
  port: 80

# MQTT server
mqtt:
  broker:  !secret mqtt_server_dev
  port:  !secret mqtt_port_dev
  username:  !secret mqtt_user_dev
  password:  !secret mqtt_password_dev

# I2C conf
i2c:
  sda: D5
  scl: D6

# Sensors
sensor:
  - platform: wifi_signal
    name: "dsleep_mini_d1_1 Signal Wi-Fi"
    update_interval: 5s
    on_value:
      if:
        condition:
          wifi.connected:
        then:
          - delay: 2s
          - logger.log: Je suis connected et envoie la sauce !
          - delay: 2s
          - logger.log: Je vais dormir !
          - deep_sleep.enter: deep_sleep_1
        else:
          - logger.log: WiFi not Antoine connected!
    
    
    
    
    
  - platform: uptime
    name: "dsleep_mini_d1_1 uptime"
    update_interval: 5s
  - platform: htu21d
    temperature:
      name: "dsleep_mini_d1_1 Température"
    humidity:
      name: "dsleep_mini_d1_1 Humidité"
    update_interval: 5s
  - platform: adc
    pin: VCC
    name: "dsleep_mini_d1_1 VCC Voltage"
    update_interval: 5s

# Deep Sleep
deep_sleep:
  run_duration: 30s
  sleep_duration: 5s
  id: deep_sleep_1
  
  
