# zf210505.0044
# sources: 
# https://community.home-assistant.io/t/using-ttgo-epaper-display-with-esphome/168877
# https://github.com/esphome/issues/issues/1458

esphome:
  name: elink_1
  platform: ESP32
  board: esp32dev

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "elink_1 Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


spi:
  clk_pin: 18
  mosi_pin: 23

time:
  - platform: sntp
    id: sntp_time

font:
  - file: "Ldfcomicsans-jj7l.ttf"
    id: font_cs
    size: 20
  - file: "arial_th.ttf"
    id: font_arth
    size: 16

display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
#    model: 2.90inv2    #ceci marche avec mon e-link zf210505.0002
    model: 2.90inv2

#    rotation: 0°
    rotation: 90°
    full_update_every: 1
    update_interval: 60s

    lambda: |-
      it.print(0, 10, id(font_cs), "Hello zuzu 004459 !");
      it.strftime(122, 50, id(font_cs), TextAlign::TOP_CENTER, "%H:%M:%S", id(sntp_time).now());
      it.strftime(122, 98, id(font_cs), TextAlign::TOP_CENTER, "%A %B %d", id(sntp_time).now());



