# zf210510.1535
# sources: 
# https://community.home-assistant.io/t/using-ttgo-epaper-display-with-esphome/168877
# https://github.com/esphome/issues/issues/1458
# https://github.com/lewisxhe/Esp-badge/blob/3dcb646971/schematic/T5_V2.3.pdf
# http://www.lilygo.cn/prod_view.aspx?TypeId=50031&Id=1149&FId=t3:50031:3


esphome:
  name: elink_1
  platform: ESP32
  board: esp32dev

# Configuration WIFI
wifi:
  networks:
  - ssid: !secret wifi_ssid
  - password: !secret wifi_password
  - ssid: !secret wifi_ssid2
  - password: !secret wifi_password2
  - ssid: !secret wifi_ssid3
  - password: !secret wifi_password3
  - ssid: !secret wifi_ssid4
  - password: !secret wifi_password4
  - ssid: !secret wifi_ssid5
  - password: !secret wifi_password5

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "elink_1 Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time



sensor:
  - platform: wifi_signal
    name: "tst_d1_disp1 Signal Wi-Fi"
    update_interval: 60s
  - platform: uptime
    name: "tst_d1_disp1 uptime"
    update_interval: 60s
  - platform: homeassistant
    name: "tst_d1_disp1 Outside Temp"
    id: outside_temperature
    entity_id: sensor.weather_temp
#    internal: true
  - platform: homeassistant
    name: "tst_d1_disp1 Inside Temp"
    entity_id: sensor.th5_temperature
    id: inside_temperature
  - platform: homeassistant
    name: "tst_d1_disp1 TVOC"
    entity_id: sensor.co2_72_tvoc
    id: tvoc




font:
  - file: 'arialn.ttf'
    id: font1
    size: 10
  - file: 'arialn.ttf'
    id: font2
    size: 13
  - file: "Ldfcomicsans-jj7l.ttf"
    id: font_cs
    size: 20
#  - file: "arial_th.ttf"
#    id: font_arth
#    size: 16

spi:
  clk_pin: 18
  mosi_pin: 23

display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
#    model: 2.90inv2    #c'est ceci qui marche avec mon e-link zf210505.0002
    model: 2.90inv2
    rotation: 90°
    full_update_every: 1
    update_interval: 15s

#   J'ai comme résolution 250x122 !
    lambda: |-
      it.print(0, 4, id(font2), TextAlign::TOP_LEFT, "Hello zuzu 154831 !");
      it.print(0, 130, id(font2), TextAlign::BOTTOM_LEFT, "ver 210510.160326");
      it.strftime(250, 130, id(font2), TextAlign::BOTTOM_RIGHT, "%A %d%B , %H:%M:%S", id(sntp_time).now());

      // Print inside temperature (from homeassistant sensor)
      it.printf(0, 15, id(font1), TextAlign::TOP_LEFT, "In side");
      if (id(inside_temperature).has_state()) {
        it.printf(64, 7, id(font1), TextAlign::BASELINE_RIGHT , "%.1f°C", id(inside_temperature).state);
      }



#      it.printf(32, 0, id(font1), TextAlign::TOP_CENTER, "Hello Zuzu");
#      it.print(0, 10, id(font_cs), "Hello zuzu 135809 !");
#      it.strftime(122, 105, id(font_cs), TextAlign::TOP_CENTER, "%A %B %d", id(sntp_time).now());
#      it.strftime(122, 50, id(font_cs), TextAlign::TOP_CENTER, "%H:%M:%S", id(sntp_time).now());
#      it.print(0, 5, id(font2), "Hello zuzu 154831 !");
#      it.printf(32, 0, id(font1), TextAlign::TOP_CENTER, "Hello Zuzu");
#      it.print(0, 5, id(font2), TextAlign::TOP_LEFT, "Hello zuzu 154831 !");
#      it.strftime(250, 130, id(font2), TextAlign::BOTTOM_RIGHT, "%A %d%B , %H:%M:%S", id(sntp_time).now());
#      it.strftime(122, 105, id(font2), TextAlign::TOP_CENTER, "%A %B %d", id(sntp_time).now());

