#------------------------------
#-- energy-meter-1.yaml
#-- Mesures de puissance de mes grands consommateurs (cuisinière et charge voiture)
#-- La mesure se fait simplement avec 3x transfos de courant clips avec un ADC i2C et un mini d1
#-- zf220712.1438
#--


# sources: 
# Hardware utilisé pour ce projet: https://github.com/zuzu59/esphome_home5/tree/master/0_Projets/Mesure_courant_clip
# EspHome convertisseur ADC ADS1115: https://esphome.io/components/sensor/ads1115.html
# Simulateur électronique: https://www.falstad.com/circuit/
# Le petit transfo clip de courant a un rapport de 25mA à 20A, soit 0.025/20=0.00125 soit encore 1/800
# Donc à 16A, il donnera un courant de 20mA



esphome:
  name: energy-meter-1
esp8266:
  board: d1_mini

# Configuration WIFI
# On le force sur apzuzu6, plus stable
wifi:
  ssid: !secret wifi_ssid_apzuzu6
  password: !secret wifi_pass_apzuzu6

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "energy-meter-1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80




i2c:
  sda: D2
  scl: D1
  scan: False


ads1115:
  - address: 0x48
#    continuous_mode: True


# Définition des Switch's
switch:
  - platform: gpio
    name: "energy-meter-1 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "energy-meter-1 Restart"


# Définitions des texts sensors
text_sensor:
  - platform: version
    name: "energy-meter-1 Version"

  - platform: wifi_info
    ip_address:
      name: energy-meter-1 IP Address
      id: wifi_ip
    ssid:
      name: energy-meter-1 Connected SSID
      id: wifi_ssid


# Définitions des sensors
sensor:
  - platform: wifi_signal
    name: "energy-meter-1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "energy-meter-1 uptime"
    update_interval: 60s

  - platform: ads1115
    name: "energy-meter-1-A0"
    multiplexer: 'A0_GND'
    gain: 4.096
    accuracy_decimals: 2
    update_interval: 5s
    unit_of_measurement: "A"
    icon: "mdi:flash"
    filters:
    - calibrate_polynomial:
        degree: 3
        datapoints:
          - 0.17 -> 0.35
          - 1.04 -> 1.30
          - 2.30 -> 5.13
          - 3.25 -> 10.24
    - lambda: |-
        if (x <= 0.32) {
          return 0.0;
        } else {
          return x;
        }

  - platform: ads1115
    name: "energy-meter-1-A1"
    multiplexer: 'A1_GND'
    gain: 4.096
    accuracy_decimals: 2
    update_interval: 5s
    unit_of_measurement: "A"
    icon: "mdi:flash"
    filters:
    - calibrate_polynomial:
        degree: 3
        datapoints:
          - 0.06 -> 0.35
          - 0.74 -> 1.30
          - 2.11 -> 5.13
          - 3.00 -> 10.24
    - lambda: |-
        if (x <= 0.29) {
          return 0.0;
        } else {
          return x;
        }

  - platform: ads1115
    name: "energy-meter-1-A2"
    multiplexer: 'A2_GND'
    gain: 4.096
    accuracy_decimals: 2
    update_interval: 5s
    unit_of_measurement: "A"
    icon: "mdi:flash"
    filters:
    - calibrate_polynomial:
        degree: 3
        datapoints:
          - 0.07 -> 0.35
          - 0.72 -> 1.30
          - 2.08 -> 5.13
          - 3.00 -> 10.24
    - lambda: |-
        if (x <= 0.27) {
          return 0.0;
        } else {
          return x;
        }

  - platform: ads1115
    name: "energy-meter-1-A3"
    multiplexer: 'A3_GND'
    gain: 4.096
    accuracy_decimals: 2
    update_interval: 5s
    unit_of_measurement: "A"
    icon: "mdi:flash"
    filters:
    - calibrate_polynomial:
        degree: 3
        datapoints:
          - 0.09 -> 0.35
          - 0.83 -> 1.30
          - 2.09 -> 5.13
          - 3.00 -> 10.24
    - lambda: |-
        if (x <= 0.29) {
          return 0.0;
        } else {
          return x;
        }


