#------------------------------
#-- energy_meter_ldr_1.yaml
#-- Petit code générique minimaliste pour des projets à base d'esp mini d1
#-- ATTENTION, la LED builting et le sensor pulse sont 'cachés' (internal: true) à cause que cela rempli l'history pour rien
#-- location: tableau électrique
#-- zf230928.1938
#--
# sources: 
# https://esphome.io/components/sensor/pulse_meter.html#converting-units  
# https://esphome.io/cookbook/power_meter.html


esphome:
  name: energy_meter_ldr_1

esp8266:
  board: d1_mini

# Configuration WIFI
wifi:
  fast_connect: true
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "energy_meter_ldr_1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    # level: VERBOSE

# Enable Home Assistant API
api:
#  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


# Définition des Switch's
switch:
  - platform: gpio
    name: "energy_meter_ldr_1 LED"
    inverted: True
    id: led
    pin: D4
    internal: true

  - platform: restart
    name: "energy_meter_ldr_1 Restart"


# Définition des Sensors
sensor:
  - platform: wifi_signal
    name: "energy_meter_ldr_1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "energy_meter_ldr_1 uptime"
    update_interval: 15s

  - platform: pulse_meter
    name: 'energy_meter_ldr_1_power'
    id: energy_meter_ldr_1_power
    pin: D1
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    accuracy_decimals: 0
    internal_filter: 50ms
    internal_filter_mode: edge
    timeout: 30s
    filters:
      - multiply: 60       # Facteur de conversion durée impulsion (1000 pulses per kWh)
      # - sliding_window_moving_average:
      #     window_size: 3
      #     send_every: 3


# Définition des Sensors text
text_sensor:
  - platform: version
    name: "energy_meter_ldr_1 Version 2311"

  - platform: wifi_info
    ip_address:
      name: energy_meter_ldr_1 IP Address
      id: wifi_ip
    ssid:
      name: energy_meter_ldr_1 Connected SSID
      id: wifi_ssid


# Définition des binary sensors
binary_sensor:
  - platform: gpio
    name: "energy_meter_ldr_1_pulse"
    pin:
      number: D2
      inverted: true
    on_press:
      - switch.turn_on: led
      - delay: 100ms
      - switch.turn_off: led
    internal: true

