#------------------------------
#-- nrj_meter_ldr_1.yaml
#-- Petit code générique minimaliste pour des projets à base d'esp mini d1
#-- blablabla
#-- location: xxx
#-- zf221023.1933
#--
# sources: 
# ...

esphome:
  name: nrj_meter_ldr_1

esp8266:
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32-ble-hub1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


# Définition des Switch's
switch:
  - platform: gpio
    name: "nrj_meter_ldr_1 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "nrj_meter_ldr_1 Restart"


# Définition des Sensors
sensor:
  - platform: wifi_signal
    name: "nrj_meter_ldr_1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "nrj_meter_ldr_1 uptime"
    update_interval: 60s

  - platform: pulse_counter
    name: 'NRJ Meter LDR 1 Power'
    id: nrj_meter_ldr_1_power
    pin: D1
    unit_of_measurement: 'W'
    update_interval: 10s    # Très important car c'est ici que l'on intègre sur une minute !
    filters:
      - multiply: 1       # Facteur de conversion durée impulsion / litres minutes
      # - sliding_window_moving_average:
      #     window_size: 5
      #     send_every: 5


# Définition des Sensors text
text_sensor:
  - platform: version
    name: "nrj_meter_ldr_1 Version 1150"

  - platform: wifi_info
    ip_address:
      name: nrj_meter_ldr_1 IP Address
      id: wifi_ip
    ssid:
      name: nrj_meter_ldr_1 Connected SSID
      id: wifi_ssid


# Définition des binary sensors
binary_sensor:
  - platform: gpio
    name: "NRJ Meter LDR 1"
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.turn_on: led
      - delay: 2s
      - switch.turn_off: led
