#------------------------------
#-- factory-reset.yaml
#-- Petit code pour faire un factory reset de l'ESP
#-- zf221018.0034
#--
# sources: 
# https://esphome.io/components/switch/factory_reset.html

esphome:
  name: factory-reset

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "RLfCRbbzQlooB82WC82wIm+tHkYULOuL2jQvir4QJ3o="

ota:
  password: "b45833112ad8283419b46067487c2099"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Factory-Reset Fallback Hotspot"
    password: "41CfoSbA2NyN"

captive_portal:

# WEB Server
web_server:
  port: 80

switch:
  - platform: factory_reset
    name: Restart with Factory Default Settings


    