substitutions:
  name: m5stack-atom-echo-80b508
  friendly_name: M5Stack Atom Echo 80b508
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: DJjPQUFEZ0aHErezhcvtwTV3QPQuYj41bJENAGWOrac=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
