#------------------------------
#-- ow-th-solar.yaml
#-- Mesures de températures de mon installation solaire thermique SEBASOL à l'aide de sondes 1-wire DS18B20
#-- ATTENTION, avec les nouveaux DS18B20 chinois, il faut ABSOLUMENT les câbler en mode 3 fils !
#-- zf210804.1042, zf220705.0731
#--


# sources: 
# https://esphome.io/components/sensor/dallas.html

esphome:
  name: ow-th-solar
  platform: ESP8266
  board: nodemcuv2

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu6_domo
  password: !secret wifi_pass_apzuzu6_domo
  reboot_timeout: 30min

#  use_address: 1w_th_solar.local

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ow-th-solar Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: false

# Enable Home Assistant API
api:
  password: !secret api_password
  reboot_timeout: 60min

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80



# Configuration du 1-wire
dallas:
  - pin: D2
    update_interval: 60s


# Définition des Switch's
switch:
  - platform: gpio
    name: "ow-th-solar LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "ow-th-solar Restart"


# Définition du bouton physique
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "ow-th-solar button"
    on_press:
      - switch.toggle: led


# Définitions des texts sensors
text_sensor:
  - platform: version
    name: "ow-th-solar Version"

  - platform: wifi_info
    ip_address:
      name: ow-th-solar IP Address
      id: wifi_ip
    ssid:
      name: ow-th-solar Connected SSID
      id: wifi_ssid


# Sensors
sensor:
  - platform: wifi_signal
    name: "ow-th-solar Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "ow-th-solar uptime"
    update_interval: 60s

  - platform: dallas
    address: 0x7E0300A279AFA028
    name: "ow-th-solar aller"

  - platform: dallas
    address: 0x860301A279FFE428
    name: "ow-th-solar retour"

  - platform: dallas
    address: 0x710301A279230C28
    name: "ow-th-solar boiler2"

  - platform: dallas
    address: 0xD80301A279E37228
    name: "ow-th-solar boiler1"

  - platform: dallas
    address: 0xCC0301A2793FD328
    name: "ow-th-solar consigne"

  - platform: dallas
    address: 0xEE0301A27920E728
    name: "ow-th-solar froid"

  - platform: dallas
    address: 0xA40301A279F37228
    name: "ow-th-solar ext nord"


