#------------------------------
#-- ow-th-ext-sud.yaml
#-- Petite sonde de température 1-wire DS18B20 pour mesurer la température au sud sous le balcon
#-- zf230928.1849
#--

# sources: 
# 
# IMPORTANT:  il faut ponter les pin D1 et D2 afin de pouvoir bénéficier de la pull up interne de D1 pour D2,
#             car il n'y a pas de possibilité d'avoir une pull up interne dans la pin 1-wire !
#             Cela évite de devoir souder une résistance pour alimenter la sonde 1-wire

esphome:
  name: ow-th-ext-sud
  platform: ESP8266
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu6
  password: !secret wifi_pass_apzuzu6

#  use_address: 1w_th_ext_sud.local

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ow-th-ext-sud Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: false


# Enable Home Assistant API
api:
#  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80
#  version: 1





# Configuration 1-wire pour les capteurs de température DS18B20
dallas:
  - pin: D2
    update_interval: 30s


# Définition des Switch's
switch:
  - platform: gpio
    name: "ow-th-ext-sud LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "ow-th-ext-sud Restart"


# Définition des binary sensors
binary_sensor:
  - platform: gpio
    name: "ow-th-ext-sud pull up"
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: True


# Définitions des texts sensors
text_sensor:
  - platform: version
    name: "ow-th-ext-sud Version"

  - platform: wifi_info
    ip_address:
      name: "ow-th-ext-sud IP Address"
      id: wifi_ip
    ssid:
      name: "ow-th-ext-sud Connected SSID"
      id: wifi_ssid


# Définition des inputs numbers
number:
  - platform: template
    name: "ow-th-ext-sud Température Calibration"
    restore_value: true
    optimistic: true
    min_value: -10
    max_value: +10
    step: 0.05
    initial_value: 0.65
    unit_of_measurement: "°K"
    id: th_ext_sud_temperature_calibration


# Définitions des Sensors
sensor:
  - platform: wifi_signal
    name: "ow-th-ext-sud Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "ow-th-ext-sud Uptime"
    update_interval: 10s

# Température aller
  - platform: dallas
    address: 0xd60000059fd9f328
    name: "ow-th-ext-sud temp"
    id: th_ext_sud_temp
    filters:
        - lambda: return ( x - (id(th_ext_sud_temperature_calibration).state /1) );







