#------------------------------
#-- pzem-test-1.yaml
#-- Petits tests d'un module power-meter PZEM-004T V3
#-- 
#-- zf210719.1813
#--


# sources: 
# https://esphome.io/components/sensor/pzemac.html


esphome:
  name: pzem-test-1
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  networks:
  
    - ssid: !secret wifi_ssid_apzuzu7
    - password: !secret wifi_pass_apzuzu7
    
    - ssid: !secret wifi_ssid_apzuzu6
    - password: !secret wifi_pass_apzuzu6
    
    - ssid: !secret wifi_ssid_3G_zf
    - password: !secret wifi_pass_3G_zf2
    
    - ssid: !secret wifi_ssid_3G_zf2
    - password: !secret wifi_pass_3G_zf2
    
    - ssid: !secret wifi_ssid_3g_s7
    - password: !secret wifi_pass_3g_s7
    
    - ssid: !secret wifi_ssid_apzuzu6_EXT
    - password: !secret wifi_pass_apzuzu6_EXT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "pzem-test-1 Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# WEB Server
web_server:
  port: 80

# Définition des Switch's
switch:
  - platform: gpio
    name: "pzem-test-1 LED"
    inverted: True
    id: led
    pin: D4
  - platform: restart
    name: "pzem-test-1 Restart"

# Définition des binary sensors
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "pzem-test-1 button"
    on_press:
      - switch.toggle: led

# Définitions des texts sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "pzem-test-1 IP Address"
      id: wifi_ip
    ssid:
      name: "pzem-test-1 Connected SSID"
      id: wifi_ssid

# Définitions des Sensors
sensor:
  - platform: wifi_signal
    name: "pzem-test-1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "pzem-test-1 Uptime"
    update_interval: 10s

  - platform: pzemac
    address: 2
    current:
      name: "PZEM-004T V3 Current"
    voltage:
      name: "PZEM-004T V3 Voltage"
    energy:
      name: "PZEM-004T V3 Energy"
    power:
      name: "PZEM-004T V3 Power"
    frequency:
      name: "PZEM-004T V3 Frequency"
    power_factor:
      name: "PZEM-004T V3 Power Factor"
    update_interval: 5s

uart:
  rx_pin: D1    #GPIO5   TX du PZEM
  tx_pin: D2    #GPIO4   RX du PZEM
  baud_rate: 9600


