#------------------------------
#-- rfbridge1.yaml
#-- Tests du bridge RF de SonOff
#-- J'essaie d'apprendre un code de la remote de mon store banne et de le rejouer
#-- zf220815.1022
#--
# sources: 
# Hardware utilisé pour ce projet (mais attention en version V2 R2.2 !): https://sonoff.tech/product/smart-home-security/rf-bridge/
# Comme plus compatible pour Tasmota depuis fin 2021, il faut utiliser ceci:
# https://community.home-assistant.io/t/new-sonoff-rf-bridge-board-need-flashing-help/344326
# Oscilloscope pour visualiser les trames 433MHz: https://dbuezas.github.io/esphome-remote_receiver-oscilloscope/



esphome:
  name: rfbridge1

esp8266:
  board: esp8285

# Configuration WIFI
# On le force sur apzuzu7, plus stable
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "rfbridge1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80

#status_led:
#  pin:
#    number: GPIO13
#    inverted: yes





# USBRX = GPIO4 ---> receiver
# USBTX = GPIO5 ---> trasmitter

# receiver = pin 5 of the 8-legged chip (the one closer to the wifi antenna)
# transmitter = pin 4 of the 6-legged chip (closest to r12)

# this will log received commands, and can also transmit. Read up here:
# https://esphome.io/components/remote_transmitter.html#remote-setting-up-rf

remote_receiver:
  pin:
    number: GPIO04
#    inverted: true
  dump:
#    - rc_switch
    - raw
  tolerance: 50%
  filter: 35us
  idle: 4ms
  buffer_size: 2kb

remote_transmitter:
  pin: GPIO05
  carrier_duty_percent: 100%




# Définitions des texts sensors
text_sensor:
  - platform: version
    name: "rfbridge1 Version"

  - platform: wifi_info
    ip_address:
      name: rfbridge1 IP Address
      id: wifi_ip
    ssid:
      name: rfbridge1 Connected SSID
      id: wifi_ssid


# Définitions des sensors
sensor:
  - platform: wifi_signal
    name: "rfbridge1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "rfbridge1 uptime"
    update_interval: 60s


# Définition des Switch's
switch:
  - platform: gpio
    name: "rfbridge1 LED"
    inverted: True
    id: led
    pin: GPIO13

  - platform: restart
    name: "rfbridge1 Restart"



  - platform: template
    name: RF Button 1
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '001011100010101000000010'
          protocol: 1
          repeat:
            times: 5
            wait_time: 100ms

  - platform: template
    name: RF Button 2
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '001011100010101000000010'
          protocol: 2
          repeat:
            times: 5
            wait_time: 100ms







  - platform: template
    name: RF Button 3
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [
                362, -1015, 365, -1013, 996, -386, 357, -1014, 998, -384, 993, -386, 989, -386, 359, 
                -1013, 371, -1006, 360, -1018, 996, -384, 357, -1015, 1000, -382, 359, -1014, 665, 
                -715, 364, -1008, 362, -1020, 355, -1016, 362, -1015, 364, -1010, 363, -1013, 365, 
                -1016, 992, -386, 358, -1010, 362
           ] 
          repeat:
            times: 4
 
         

  - platform: template
    name: RF Button 4
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [
                362, -1013, 362, -1016, 993, -386, 358, -1017, 996, -384, 991, -384, 996, -381, 
                355, -1020, 360, -1015, 362, -1034, 985, -374, 357, -1018, 994, -385, 358, -1017, 
                997, -381, 359, -1016, 362, -1013, 359, -1017, 361, -1015, 364, -1013, 362, -1013, 
                363, -1015, 996, -381, 357, -1013, 357
           ] 
          repeat:
            times: 4









