#------------------------------
#-- rfbridge1.yaml
#-- Tests du bridge RF de SonOff
#-- J'essaie d'apprendre un code de la remote de mon store banne et de le rejouer
#-- zf220815.1146
#--
# sources: 
# Hardware utilisé pour ce projet (mais attention en version V2 R2.2 !): https://sonoff.tech/product/smart-home-security/rf-bridge/
# Comme plus compatible pour Tasmota depuis fin 2021, il faut utiliser ceci:
# https://community.home-assistant.io/t/new-sonoff-rf-bridge-board-need-flashing-help/344326
# Oscilloscope pour visualiser les trames 433MHz: https://dbuezas.github.io/esphome-remote_receiver-oscilloscope/



esphome:
  name: rfbridge1

esp8266:
  board: esp8285

# Configuration WIFI
# On le force sur apzuzu7, plus stable
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "rfbridge1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80

#status_led:
#  pin:
#    number: GPIO13
#    inverted: yes





# USBRX = GPIO4 ---> receiver
# USBTX = GPIO5 ---> trasmitter

# receiver = pin 5 of the 8-legged chip (the one closer to the wifi antenna)
# transmitter = pin 4 of the 6-legged chip (closest to r12)

# this will log received commands, and can also transmit. Read up here:
# https://esphome.io/components/remote_transmitter.html#remote-setting-up-rf

remote_receiver:
  pin:
    number: GPIO04
#    number: GPIO13
#    inverted: true
  dump: all
#    - rc_switch
#    - raw
  tolerance: 50%
  filter: 35us
  idle: 4ms
  buffer_size: 2kb



remote_transmitter:
  pin: GPIO05
  carrier_duty_percent: 100%




# Définitions des texts sensors
text_sensor:
  - platform: version
    name: "rfbridge1 Version"

  - platform: wifi_info
    ip_address:
      name: rfbridge1 IP Address
      id: wifi_ip
    ssid:
      name: rfbridge1 Connected SSID
      id: wifi_ssid


# Définitions des sensors
sensor:
  - platform: wifi_signal
    name: "rfbridge1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "rfbridge1 uptime"
    update_interval: 60s


# Définition des Switch's
switch:
  - platform: gpio
    name: "rfbridge1 LED"
    inverted: True
    id: led
    pin: GPIO13

  - platform: restart
    name: "rfbridge1 Restart"


  - platform: template
    name: RF remote chinoise ON
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [
                362, -1013, 362, -1016, 993, -386, 358, -1017, 996, -384, 991, -384, 996, -381, 
                355, -1020, 360, -1015, 362, -1034, 985, -374, 357, -1018, 994, -385, 358, -1017, 
                997, -381, 359, -1016, 362, -1013, 359, -1017, 361, -1015, 364, -1013, 362, -1013, 
                363, -1015, 996, -381, 357, -1013, 357
           ] 
          repeat:
            times: 4






  - platform: template
    name: RF Button 1
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '001011100010101000000010'
          protocol: 1
          repeat:
            times: 5
            wait_time: 100ms

  - platform: template
    name: RF Button 2
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          code: '001011100010101000000010'
          protocol: 2
          repeat:
            times: 5
            wait_time: 100ms







  - platform: template
    name: RF Button 3
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [
            -1490, 725, -362, 362, -719, 722, -364, 363, -718, 363, -719, 725, -363, 
            363, -717, 722, -365, 719, -364, 717, -367, 717, -365, 371, -229, 129, 
            -355, 719, -365, 430, -179, 122, -352, 360, -729, 360, -714, 722, -365, 
            719, -365, 717, -364, 362, -719, 363, -720, 721, -367, 719, -362, 720, 
            -364, 362, -718, 364, -719, 365, -718, 367, -715, 365, -719, 282, -160, 
            282, -361, 364, -717, 724, -362, 364, -717, 363, -720, 366, -720, 724, 
            -362, 359, -720, 364, -719, 363, -720, 723, -3898, 724, -362, 362, -719, 
            721, -366, 366, -714, 363, -721, 723, -364, 362, -717, 722, -367, 715, 
            -369, 717, -364, 720, -364, 722, -362, 720, -364, 719, -365, 719, -365, 
            364, -715, 364, -151, 211, -360, 379, -190, 158, -355, 719, -363, 361, 
            -720, 364, -718, 723, -362, 718, -366, 722, -365, 359, -719, 365, -717, 
            284, -800, 365, -717, 364, -719, 720, -367, 362, -719, 725, -364, 360, 
            -718, 368, -714, 367, -715, 722, -364, 362, -720, 364, -720, 364, -717, 722
           ] 
          repeat:
            times: 4
#    inverted: true
 
 
 
  - platform: template
    name: RF Button 4
    turn_on_action:
#      - remote_transmitter.transmit_pronto:
#          data: "0000 006D 0001 0000 0018 06C3"

      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0001 0000 0018 06C3 0000 006D 0029 0000 000D 0009 0006 000F 000D 001C 001B 000F 000D 
          001C 000D 001C 001B 000F 000D 001C 001B 000F 001B 000F 001B 000F 001B 
          000F 001B 000F 001B 000F 001B 000F 001B 000F 000D 001C 001B 000F 001B 
          000F 001B 000F 000D 001C 000D 001C 001B 000F 001B 000F 001B 000F 000D 
          001C 000D 001C 000D 001C 000D 001C 000D 001C 001B 000F 000D 001C 001B 
          000F 000D 001C 000D 001D 000D 001C 001B 000F 000D 001C 000D 001C 000C 
          001D 001B 06C3"
          repeat:
            times: 8

#[11:35:35][D][remote.pronto:229]: Received Pronto: data=0000 006D 0001 0000 0018 06C3
#[11:35:35][D][remote.pronto:229]: Received Pronto: data=0000 006D 0029 0000 000D 0009 0006 000F 000D 001C 001B 000F 000D 001C 000D 001C 001B 000F 000D 001C 001B 000F 001B 000F 001B 000F 001B 000F 001B 000F 001B 000F 001B 000F 001B 000F 000D 001C 001B 000F 001B 000F 001B 000F 000D 001C 000D 001C 001B 000F 001B 000F 001B 000F 000D 001C 000D 001C 000D 001C 000D 001C 000D 001C 001B 000F 000D 001C 001B 000F 000D 001C 000D 001D 000D 001C 001B 000F 000D 001C 000D 001C 000C 001D 001B 06C3



      
    

         










