#------------------------------
#-- rfbridge1.yaml
#-- Tests du bridge RF de SonOff
#-- J'essaie d'apprendre un code de la remote de mon store banne et de le rejouer
#-- zf220815.1731
#--
# sources: 
# Hardware utilisé pour ce projet (mais attention en version V2 R2.2 !): https://sonoff.tech/product/smart-home-security/rf-bridge/
# Comme plus compatible pour Tasmota depuis fin 2021, il faut utiliser ceci:
# https://community.home-assistant.io/t/new-sonoff-rf-bridge-board-need-flashing-help/344326
# Oscilloscope pour visualiser les trames 433MHz: https://dbuezas.github.io/esphome-remote_receiver-oscilloscope/
# https://esphome.io/components/remote_transmitter.html#remote-setting-up-rf



esphome:
  name: rfbridge1

esp8266:
  board: esp8285

# Configuration WIFI
# On le force sur apzuzu7, plus stable
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "rfbridge1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80

#status_led:
#  pin:
#    number: GPIO13
#    inverted: yes





# USBRX = GPIO4 ---> receiver
# USBTX = GPIO5 ---> trasmitter

# receiver = pin 5 of the 8-legged chip (the one closer to the wifi antenna)
# transmitter = pin 4 of the 6-legged chip (closest to r12)

# this will log received commands, and can also transmit. Read up here:
# https://esphome.io/components/remote_transmitter.html#remote-setting-up-rf

remote_receiver:
  pin:
    number: GPIO04
#  dump: raw
  tolerance: 50%
  filter: 10us
  idle: 10ms
  buffer_size: 2kb



remote_transmitter:
  pin: GPIO05
  carrier_duty_percent: 100%




# Définitions des texts sensors
text_sensor:
  - platform: version
    name: "rfbridge1 Version"

  - platform: wifi_info
    ip_address:
      name: rfbridge1 IP Address
      id: wifi_ip
    ssid:
      name: rfbridge1 Connected SSID
      id: wifi_ssid


# Définitions des sensors
sensor:
  - platform: wifi_signal
    name: "rfbridge1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "rfbridge1 uptime"
    update_interval: 60s


# Définition des Switch's
switch:
  - platform: gpio
    name: "rfbridge1 LED"
    inverted: True
    id: led
    pin: GPIO13

  - platform: restart
    name: "rfbridge1 Restart"


  - platform: template
    name: RF1 remote Test LED ON
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [
                362, -1013, 362, -1016, 993, -386, 358, -1017, 996, -384, 991, -384, 996, -381, 
                355, -1020, 360, -1015, 362, -1034, 985, -374, 357, -1018, 994, -385, 358, -1017, 
                997, -381, 359, -1016, 362, -1013, 359, -1017, 361, -1015, 364, -1013, 362, -1013, 
                363, -1015, 996, -381, 357, -1013, 357
           ] 
          repeat:
            times: 4


  - platform: template
    name: RF1 Button up
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [
            -7817, 4830, -1489, 724, -362, 365, -717, 722, -364, 362, -717, 367, 
            -715, 724, -362, 362, -717, 724, -362, 722, -362, 720, -364, 
            719, -364, 720, -362, 720, -362, 719, -365, 719, -365, 362, 
            -717, 724, -364, 720, -363, 721, -362, 360, -719, 367, -717, 
            722, -364, 720, -362, 719, -362, 362, -720, 364, -717, 367, 
            -717, 367, -717, 364, -720, 722, -365, 361, -720, 724, -363, 
            363, -717, 367, -717, 367, -717, 722, -364, 362, -717, 367, 
            -717, 365, -719, 722,
            -7817, 4830, 
            -1489, 724, -362, 365, -717, 722, -364, 362, -717, 367, 
            -715, 724, -362, 362, -717, 724, -362, 722, -362, 720, -364, 
            719, -364, 720, -362, 720, -362, 719, -365, 719, -365, 362, 
            -717, 724, -364, 720, -363, 721, -362, 360, -719, 367, -717, 
            722, -364, 720, -362, 719, -362, 362, -720, 364, -717, 367, 
            -717, 367, -717, 364, -720, 722, -365, 361, -720, 724, -363, 
            363, -717, 367, -717, 367, -717, 722, -364, 362, -717, 367, 
            -717, 365, -719, 722,
           ] 


  - platform: template
    name: RF1 Button stop
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [
            -1483, 723, -359, 360, -714, 720, -361, 361, -714, 366, -713, 
            720, -359, 251, -827, 721, -362, 717, -362, 717, -360, 717, 
            -362, 717, -362, 719, -360, 715, -365, 714, -365, 359, -718, 
            719, -362, 717, -362, 717, -362, 363, -714, 362, -717, 720, 
            -362, 717, -362, 717, -362, 362, -716, 363, -717, 362, -717, 
            365, -717, 362, -717, 720, -362, 362, -717, 719, -362, 362, 
            -715, 722, -362, 360, -717, 719, -362, 362, -717, 720, -362, 
            360, -719, 719, 
            -7786, 4812, 
            -1486, 719, -362, 362, -717, 720, 
            -362, 360, -717, 364, -716, 721, -362, 362, -717, 719, -365, 
            717, -364, 717, -362, 720, -362, 719, -360, 717, -365, 717, 
            -362, 717, -362, 362, -717, 719, -363, 719, -362, 718, -361, 
            360, -717, 364, -717, 720, -362, 718, -363, 718, -362, 362, 
            -717, 366, -713, 364, -715, 365, -715, 364, -717, 722, -362, 
            359, -717, 720, -368, 356, -717, 722, -360, 362, -717, 719, 
            -362, 360, -718, 721, -362, 366, -713, 722
           ] 


  - platform: template
    name: RF1 Button down
    turn_on_action:
      - remote_transmitter.transmit_raw:
          code: [
            -1486, 719, -361, 361, -717, 720, -362, 362, -716, 361, -717, 
            721, -360, 362, -715, 719, -364, 716, -364, 715, -364, 717, 
            -362, 721, -361, 717, -362, 717, -362, 717, -362, 362, -717, 
            720, -359, 720, -362, 717, -362, 362, -715, 364, -717, 720, 
            -365, 716, -364, 718, -363, 361, -719, 363, -719, 362, -717, 
            365, -717, 362, -719, 720, -362, 359, -722, 717, -365, 359, 
            -717, 365, -717, 722, -362, 720, -360, 361, -719, 363, -719, 
            719, -363, 719, 
            -7793, 4818, 
            -1485, 721, -362, 360, -718, 
            721, -362, 362, -714, 365, -717, 719, -362, 360, -717, 722, 
            -365, 714, -362, 721, -361, 717, -362, 717, -362, 717, -362, 
            720, -362, 717, -362, 360, -717, 719, -362, 717, -362, 717, 
            -362, 362, -715, 362, -721, 718, -362, 717, -362, 720, -359, 
            363, -714, 365, -717, 364, -715, 365, -714, 362, -719, 720, 
            -361, 363, -715, 719, -365, 359, -717, 365, -717, 722, -362, 
            723, -357, 363, -715, 365, -717, 723, -358, 717
           ] 



binary_sensor:
  - platform: remote_receiver
    name: "RF1 Test LED ON"
    raw:
      code: [
            362, -1013, 362, -1016, 993, -386, 358, -1017, 996, -384, 991, -384, 996, -381, 
            355, -1020, 360, -1015, 362, -1034, 985, -374, 357, -1018, 994, -385, 358, -1017, 
            997, -381, 359, -1016, 362, -1013, 359, -1017, 361, -1015, 364, -1013, 362, -1013, 
            363, -1015, 996, -381, 357, -1013, 357
       ] 

