
# zf210607.1725
# sources: 
# 

esphome:
  name: solar_debit
  platform: ESP8266
  board: d1_mini

# Configuration WIFI
wifi:
  networks:
  - ssid: !secret wifi_ssid
  - password: !secret wifi_password
  - ssid: !secret wifi_ssid2
  - password: !secret wifi_password2
  - ssid: !secret wifi_ssid3
  - password: !secret wifi_password3
  - ssid: !secret wifi_ssid4
  - password: !secret wifi_password4
  - ssid: !secret wifi_ssid5
  - password: !secret wifi_password5
  - ssid: !secret wifi_ssid6
  - password: !secret wifi_password6

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "solar_debit Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


# Définition des Switch's
switch:
  - platform: gpio
    name: "solar_debit LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "solar_debit Restart"


# Définition des binary_sensor
binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    name: "solar_debit pulse"


# Définitions des texts sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: solar_debit IP Address
      id: wifi_ip
    ssid:
      name: solar_debit Connected SSID
      id: wifi_ssid


# Sensors
sensor:
  - platform: wifi_signal
    name: "solar_debit Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "solar_debit uptime"
    update_interval: 60s


