
# zf210608.1832
# sources: 
# 

esphome:
  name: solar_debit
  platform: ESP8266
  board: d1_mini

# Configuration WIFI
wifi:
  networks:
  - ssid: !secret wifi_ssid
  - password: !secret wifi_password
  - ssid: !secret wifi_ssid2
  - password: !secret wifi_password2
  - ssid: !secret wifi_ssid3
  - password: !secret wifi_password3
  - ssid: !secret wifi_ssid4
  - password: !secret wifi_password4
  - ssid: !secret wifi_ssid5
  - password: !secret wifi_password5
  - ssid: !secret wifi_ssid6
  - password: !secret wifi_password6

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "solar_debit Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80




# Définition des Switch's
switch:
  - platform: gpio
    name: "solar_debit LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "solar_debit Restart"


# Définition des binary_sensor
binary_sensor:
  - platform: gpio
    name: "solar_debit reed"
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - script.execute: watchdog_debit_minute
      - switch.turn_on: led
      - delay: 2s
      - switch.turn_off: led


# Définitions des texts sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: solar_debit IP Address
      id: wifi_ip
    ssid:
      name: solar_debit Connected SSID
      id: wifi_ssid


# Définitions des Sensors
sensor:
  - platform: wifi_signal
    name: "solar_debit Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "solar_debit Uptime"
    update_interval: 60s

  - platform: pulse_counter
    name: 'solar_debit Pulse'
    pin: D2
    unit_of_measurement: 'l/'
    update_interval: 60s
    id: my_flow_meter
#    count_mode:
#      rising_edge: DISABLE
#      falling_edge: INCREMENT
#    filters:
#     - multiply: 0.1

  - platform: integration
    name: "solar_debit Débit"
    sensor: my_flow_meter
    time_unit: min
    id: my_integration_sensor
    filters:
      - sliding_window_moving_average:
          window_size: 5
#          send_every: 5

# Définitions des Scripts
script:
  - id: watchdog_debit_minute
    mode: restart     # Fait office de watchdog
    then:
      - sensor.integration.reset:  my_integration_sensor
      - delay: 60s
      - logger.log: On reset l'intégrateur !
      - sensor.integration.reset:  my_integration_sensor
  


