#------------------------------
#-- solar_debit.yaml
#-- Petit débimètre pour mon installation solaire thermique SEBASOL
#-- Il compte les impulsions d'une ampoule REED collée sur un débimètre mécanique conventionnel
#-- zf210713.1114, zf230928.1842, zf240322.1159
#--

# sources: 
# 
# IMPORTANT: il faut ponter les pin D1 et D2 afin de pouvoir bénéficier de la pull up interne de D1 pour D2,
#            car il n'y a pas de possibilité d'avoir une pull up interne dans un pulse_counter !

esphome:
  name: solar_debit
  platform: ESP8266
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu8
  password: !secret wifi_pass_apzuzu8

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "solar_debit Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
#    level: VERBOSE

# Enable Home Assistant API
api:
#  password: !secret api_password
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 60min

# Enable OTA
ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80




# Définition des Switch's
switch:
  - platform: gpio
    name: "solar_debit LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "solar_debit Restart"


# Définition des binary sensors
binary_sensor:
  - platform: gpio
    name: "solar_debit Reed"
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.turn_on: led
      - delay: 2s
      - switch.turn_off: led


# Définitions des texts sensors
text_sensor:
  - platform: version
    name: "solar_debit Version"

  - platform: wifi_info
    ip_address:
      name: "solar_debit IP Address"
      id: wifi_ip
    ssid:
      name: "solar_debit Connected SSID"
      id: wifi_ssid


# Définitions des Sensors
sensor:
  - platform: wifi_signal
    name: "solar_debit Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "solar_debit Uptime"
    update_interval: 10s

  - platform: pulse_counter
    name: 'solar_debit Flow'
    id: my_flow_meter
    pin: D2
    unit_of_measurement: 'l/mn'
    update_interval: 60s    # Très important car c'est ici que l'on intègre sur une minute !
    filters:
      - multiply: 0.3       # Facteur de conversion durée impulsion / litres minutes
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5




