#------------------------------
#-- switch_12v_1.yaml
#-- Petit code pour piloter un petit relais 12V depuis ha à base de mini d1
#-- le relais est branché sur D1 !
#-- location: dehors pour la fontaine virtuelle pour le bruit de l'eau de fontaine
#-- zf230820.1423
#--
# sources: 
# ...

esphome:
  name: switch_12v_1

esp8266:
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu8
  password: !secret wifi_pass_apzuzu8


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "switch_12v_1 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


# Définition des Switch's
switch:
  - platform: gpio
    name: "switch_12v_1 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "switch_12v_1 Restart"

  - platform: gpio
    name: "switch_12v_1 relais1"
    inverted: True
    id: switch_12v_1_relais1
    pin: D1



# Définition des Sensors
sensor:
  - platform: wifi_signal
    name: "switch_12v_1 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "switch_12v_1 uptime"
    update_interval: 60s


# Définition des Sensors text
text_sensor:
  - platform: version
    name: "switch_12v_1 Version 1150"

  - platform: wifi_info
    ip_address:
      name: switch_12v_1 IP Address
      id: wifi_ip
    ssid:
      name: switch_12v_1 Connected SSID
      id: wifi_ssid


# Définition des inputs numbers
number:
  - platform: template
    name: "switch_12v_1 consigne alarme low"
    restore_value: true
    optimistic: true
    mode: box
    min_value: 0.0
    max_value: 0.8
    step: 0.01
    initial_value: 0.4
    unit_of_measurement: "V"
    id: switch_12v_1_consigne_alarme_low