#------------------------------
#-- th0.yaml
#-- Petit code mini manilste pour mesurer la température et l'humidité
#-- Lit la tmpérature et l'humidité du capteur HTU21D
#-- location: chambre à Chloé bureau zf
#-- zf210720.1021, zf230117.1538
#--


# sources: 
# https://esphome.io/components/sensor/htu21d.html
# Google Sheet pour la calibation: https://docs.google.com/spreadsheets/d/1iXrqRoCMJt91MejVzX4IAtF0g-0zK2hgI-jhiC7n6G8


esphome:
  name: th0
  platform: ESP8266
  board: nodemcuv2

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: th0 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Définition des Switch's
switch:
  - platform: gpio
    name: "th0 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "th0 Restart"

# Définition du bouton physique
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "th0 button"
    on_press:
      - switch.toggle: led

# WEB Server
web_server:
  port: 80

# I2C conf
i2c:
  sda: D5
  scl: D6

# Sensors
sensor:
  - platform: wifi_signal
    name: "th0 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "th0 uptime"
    update_interval: 60s

  - platform: htu21d
    temperature:
      name: "th0 Température"
    humidity:
      name: "th0 Humidité"
    update_interval: 15s

# valeur brute en volts de la photo résistance
  - platform: adc
    pin: A0
    name: "th0 luminosite en volts"
    id: th0_luminosite_en_volts
    update_interval: 2s
    unit_of_measurement: "V"

# valeur calibrée en 8 bits de la photo résistance
  - platform: template
    name: "th0 luminosite"
    update_interval: 2s
    unit_of_measurement: "/255"
    lambda: return id(th0_luminosite_en_volts).state ;
#    lambda: return id(th0_consigne_brightness).state ;
    filters:
      # linéarise la photo résistance
      - calibrate_polynomial:
         degree: 2
         datapoints:
          - 0.0-> 0.0
          - 0.4 -> 64
          - 0.8 -> 255


      # arondi le résultat
      - lambda: return floor(x);
      # filtre la valeur minimale
      - lambda: |-
          if (x >= 2) 
            return x;
          else 
            return 2;
      # filtre la valeur maximale
      - lambda: |-
          if (x <= 255) 
            return x;
          else 
            return 255;

      
# Sensors text
text_sensor:
  - platform: version
    name: "th0 Version 2330"

  - platform: wifi_info
    ip_address:
      name: th0 IP Address
      id: wifi_ip
    ssid:
      name: th0 Connected SSID
      id: wifi_ssid


# Définition des inputs numbers
number:
  - platform: template
    name: "th0 consigne brightness"
    restore_value: true
    optimistic: true
    min_value: 0.0
    max_value: 0.8
    step: 0.01
    initial_value: 0.4
    unit_of_measurement: "V"
    id: th0_consigne_brightness




