#zf210317.0127

globals:
   - id: ota_state
     type: int
     initial_value: '0'
   - id: ota_timeout
     type: int
     initial_value: '0'

interval:
  - interval: 1s
    then:
      if:
        condition:
          mqtt.connected:
        then:
          - logger.log: MQTT est connecté !
          - if:
              condition:
                lambda: 'return id(ota_state) == 1;'
              then:
                - logger.log: OTA est demandé !
                - logger.log: J'arrête le desleep !
                - deep_sleep.prevent: deep_sleep_1
              else:
                - logger.log: Je suis connected et envoie la sauce !
                - logger.log: Je vais dormir !
                - delay: 0.5s
                - deep_sleep.enter: deep_sleep_1
          - lambda: |-
              id(ota_timeout) += 1;
          - if:
              condition:
                lambda: 'return id(ota_timeout) > 12;'
              then:
                - logger.log: On est en ota timeout !
                - mqtt.publish:
                    topic: th0_8285/ota/state
                    payload: 'OFF'
                    retain: true
                - logger.log: J'ai mis state OTA à OFF !
                - logger.log: J'ai un problème, je dois dormir !
                - delay: 0.5s
                - deep_sleep.enter: deep_sleep_1
              else:
                - logger.log: On peut flasher !
        else:
          - logger.log: J'attends d'être connecté à MQTT !



# Configuration ESPhome
esphome:
  name: th0_8285
  platform: ESP8266
  board: esp8285
  on_boot:
    - switch.turn_on: led

#    - delay: 60s
#    - logger.log: J'ai un problème, je dois dormir !
#    - deep_sleep.enter: deep_sleep_1



    # - wait_until: mqtt.connected 
    # - if:
    #     condition:
    #       lambda: 'return id(ota_state) == 1;'
    #     then:
    #       - logger.log: Je vois que OTA est demandé !
    #       - mqtt.publish:
    #           topic: th0_8285/ota/state
    #           payload: 'OFF'
    #           retain: true
    #       - logger.log: J'ai mis state OTA à OFF !

    #     else:
    #       - logger.log: tutu1 !
    # - logger.log: titi1 !
    # - if:
    #     condition:
    #       mqtt.connected
    #     then:
    #       - logger.log: toto2 !
    #     else:
    #       - logger.log: tutu2 !
    # - logger.log: titi2 !
    
      
    # - wait_until: mqtt.connected 
    # - logger.log: Je suis connected et envoie la sauce !
    # - delay: 1s
    # then:
    #   - if:
    #     condition:
    #       - topic: th0_8285/ota/state
    #         payload: 'ON'
    #   then:
    #     - logger.log: Je vais dormir !
      
    # - mqtt.publish:
    #   topic: th0_8285/ota/state
    #   payload: 'OFF'
    #   retain: true
    # - delay: 1s
    # - logger.log: Je vais dormir !
    # - deep_sleep.enter: deep_sleep_1

#    on_shutdown:
#    then:
#      - logger.log: Je m'arrête !
#      - delay: 4s

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "th0_8285 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
  level: DEBUG
  logs:
    logger: INFO
    adc: INFO
    captive_portal: INFO
    deep_sleep: INFO
    htu21d: INFO
    i2c: INFO
    ota: INFO
    restart: INFO
    sensor: INFO
    switch: INFO
    switch.gpio: INFO
    uptime.sensor: INFO
    web_server: INFO
    wifi_signal.sensor: INFO
    mqtt: INFO
    mqtt.component: INFO
    mqtt.client: INFO
    mqtt.switch: INFO
    mqtt.sensor: INFO

# Enable Home Assistant API
#api:
#  password: !secret api_password

ota:
  password: !secret ota_password

# Définition des Switch's
switch:
  - platform: gpio
    name: "th0_8285 LED"
    inverted: True
    id: led
    pin: GPIO2
  - platform: restart
    name: "th0_8285 Restart"

# WEB Server
web_server:
  port: 80

# MQTT server
mqtt:
  broker:  !secret mqtt_server_dev
  port:  !secret mqtt_port_dev
  username:  !secret mqtt_user_dev
  password:  !secret mqtt_password_dev
  on_message:
    - topic: th0_8285/ota/command
      payload: 'ON'
      then:
        - logger.log: Receive OTA command !
        - mqtt.publish:
           topic: th0_8285/ota/command
           payload: 'OFF'
           retain: true
        - mqtt.publish:
           topic: th0_8285/ota/state
           payload: 'ON'
           retain: true
        - globals.set:
            id: ota_state
            value: '1'



   #       - deep_sleep.prevent: deep_sleep_1
  #       - logger.log: SLEEP mode paused !
  #       - delay: 20s
  #       - mqtt.publish:
  #         topic: th0_8285/ota/state
  #         payload: 'OFF'
  #         retain: true
  #       - logger.log: Return to SLEEP !
  #       - delay: 2s
  #       - deep_sleep.enter: deep_sleep_1

# I2C conf
i2c:
  sda: GPIO4
  scl: GPIO14

# Sensors
sensor:
  - platform: wifi_signal
    name: "th0_8285 Signal Wi-Fi"
    update_interval: 3s
#    on_value:
#      if:
#        condition:
#          mqtt.connected:
#        then:
#          - logger.log: Je suis connected et envoie la sauce !
#          - delay: 2s
#          - logger.log: Je vais dormir !
#          - deep_sleep.enter: deep_sleep_1
  - platform: uptime
    name: "th0_8285 uptime"
    update_interval: 3s
  - platform: htu21d
    temperature:
      name: "th0_8285 Température"
    humidity:
      name: "th0_8285 Humidité"
    update_interval: 3s
  - platform: adc
    pin: VCC
    name: "th0_8285 VCC Voltage"
    update_interval: 3s

# Deep Sleep
deep_sleep:
  run_duration: 10s
  sleep_duration: 10s
  id: deep_sleep_1
  