#zf210315.1543

esphome:
  name: th0_8285
  platform: ESP8266
  board: esp8285
  on_boot:
  - switch.turn_on: led


# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "th0_8285 Fallback"
    password: !secret ap_wifi_password


captive_portal:

# Enable logging
logger:
  level: DEBUG
  logs:
    logger: INFO
    adc: INFO
    captive_portal: INFO
    deep_sleep: INFO
    htu21d: INFO
    i2c: INFO
    ota: INFO
    restart: INFO
    sensor: INFO
    switch: INFO
    switch.gpio: INFO
    uptime.sensor: INFO
    web_server: INFO
    wifi_signal.sensor: INFO
    mqtt: INFO
    mqtt.component: INFO
    mqtt.client: INFO
    mqtt.switch: INFO
    mqtt.sensor: INFO
    

    
    

# Enable Home Assistant API
#api:
#  password: !secret api_password


ota:
  password: !secret ota_password

# Définition des Switch's
switch:
  - platform: gpio
    name: "th0_8285 LED"
    inverted: True
    id: led
    pin: GPIO2
  - platform: restart
    name: "th0_8285 Restart"
    
  - platform: template
    name: "th0_8285 Mode"
    id: th0_8285_mode
    
    
    

# WEB Server
web_server:
  port: 80

# MQTT server
mqtt:
  broker:  !secret mqtt_server_dev
  port:  !secret mqtt_port_dev
  username:  !secret mqtt_user_dev
  password:  !secret mqtt_password_dev
  on_message:

    - topic: th0_8285/mode/ota
      payload: 'ON'
      then:
        - logger.log: Reçu l'ordre OTA !
        - mqtt.publish:
           topic: th0_8285/mode/ota
           payload: 'OFF'
           retain: true
        - mqtt.publish:
           topic: th0_8285/mode/mode_status
           payload: 'OTA'
           retain: true
        - switch.template.publish:
           id: th0_8285_mode
           state: ON
   
        - deep_sleep.prevent: deep_sleep_1
        - delay: 20s
        - mqtt.publish:
           topic: th0_8285/mode/sleep
           payload: 'ON'
           retain: true

    - topic: th0_8285/mode/sleep
      payload: 'ON'
      then:
        - logger.log: Reçu l'ordre SLEEP !
        - mqtt.publish:
           topic: th0_8285/mode/sleep
           payload: 'OFF'
           retain: true
        - mqtt.publish:
           topic: th0_8285//mode/mode_status
           payload: 'SLEEP'
           retain: true
        - switch.template.publish:
           id: th0_8285_mode
           state: OFF
           
        - delay: 2s
        - deep_sleep.enter: deep_sleep_1


# I2C conf
i2c:
  sda: GPIO4
  scl: GPIO14

# Sensors
sensor:
  - platform: wifi_signal
    name: "th0_8285 Signal Wi-Fi"
    on_value:
      if:
        condition:
          mqtt.connected:
        then:
#            - delay: 2s
          - logger.log: Je suis connected et envoie la sauce !
          - delay: 2s
#          - logger.log: Je vais dormir !
#          - deep_sleep.enter: deep_sleep_1
        else:
          - logger.log: WiFi not Antoine connected!
    update_interval: 3s
  - platform: uptime
    name: "th0_8285 uptime"
    update_interval: 3s
  - platform: htu21d
    temperature:
      name: "th0_8285 Température"
    humidity:
      name: "th0_8285 Humidité"
    update_interval: 3s
  - platform: adc
    pin: VCC
    name: "th0_8285 VCC Voltage"
    update_interval: 3s

# Deep Sleep
deep_sleep:
  run_duration: 7s
  sleep_duration: 10s
  id: deep_sleep_1
  


