#------------------------------
#-- th2.yaml
#-- Petit code pour monitorer la température et l'humidité dans une pièce
#-- location: garage porte nord
#-- zf230219.2334
#--
# sources: 
# https://esphome.io/components/sensor/htu21d.html

esphome:
  name: th2

esp8266:
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # networks:
  
  #   - ssid: !secret wifi_ssid_apzuzu7
  #   - password: !secret wifi_pass_apzuzu7
    
  #   - ssid: !secret wifi_ssid_apzuzu6
  #   - password: !secret wifi_pass_apzuzu6

  #   - ssid: !secret wifi_ssid_3G_zf
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3G_zf2
  #   - password: !secret wifi_pass_3G_zf2
    
  #   - ssid: !secret wifi_ssid_3g_s7
  #   - password: !secret wifi_pass_3g_s7
    
  #   - ssid: !secret wifi_ssid_apzuzu6_EXT
  #   - password: !secret wifi_pass_apzuzu6_EXT


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "th2 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    # level: VERBOSE

# Enable Home Assistant API
api:
#  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80

# I2C conf
i2c:
  sda: D5
  scl: D6


# Définition des Switch's
switch:
  - platform: gpio
    name: "th2 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "th2 Restart"


# Définition des Sensors
sensor:
  - platform: wifi_signal
    name: "th2 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "th2 uptime"
    update_interval: 15s

  - platform: htu21d
    temperature:
      name: "th2 Température"
    humidity:
      name: "th2 Humidité"
    update_interval: 60s

# valeur brute en volts de la photo résistance
  - platform: adc
    pin: A0
    name: "th2 luminosite en volts"
    id: th2_luminosite_en_volts
    update_interval: 2s
    unit_of_measurement: "V"

# valeur calibrée en 8 bits de la photo résistance
  - platform: template
    name: "th2 luminosite"
    update_interval: 2s
    unit_of_measurement: "/255"
    lambda: return id(th2_luminosite_en_volts).state ;
#    lambda: return id(th2_consigne_brightness).state ;
    filters:
      # linéarise la photo résistance
      - calibrate_polynomial:
         degree: 2
         datapoints:
          - 0.0-> 0.0
          - 0.4 -> 64
          - 0.9 -> 255

      # arondi le résultat
      - lambda: return floor(x);
      # filtre la valeur minimale
      - lambda: |-
          if (x >= 2) 
            return x;
          else 
            return 2;
      # filtre la valeur maximale
      - lambda: |-
          if (x <= 255) 
            return x;
          else 
            return 255;

# Définition des Sensors text
text_sensor:
  - platform: version
    name: "th2 Version 1257"

  - platform: wifi_info
    ip_address:
      name: th2 IP Address
      id: wifi_ip
    ssid:
      name: th2 Connected SSID
      id: wifi_ssid

