esphome:
  name: th2_8285
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "1"
  password: "1"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Th2 8285 Fallback Hotspot"
    password: "bCsKKM8D9iQh"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "1"

ota:
  password: "1"
