#zf210210.1600

esphome:
  name: th5
  platform: ESP8266
  board: nodemcuv2

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "th5 Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Définition des Switch's
switch:
  - platform: gpio
    name: "th5 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "th5 Restart"

# Définition du bouton physique
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "th5 button"
    on_press:
      - switch.toggle: led

# WEB Server
web_server:
  port: 80




# I2C conf
i2c:
  sda: D5
  scl: D6

# Sensors
sensor:
  - platform: wifi_signal
    name: "th5 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "th5 uptime"
    update_interval: 60s

  - platform: htu21d
    temperature:
      name: "th5 Température"
    humidity:
      name: "th5 Humidité"
    update_interval: 5s

