#------------------------------
#-- th6.yaml
#-- Petit code mini manilste pour mesurer la température et l'humidité
#-- Lit la tmpérature et l'humidité du capteur HTU21D
#-- location: cave vers interrupteur lumière
#-- zf210720.1023, zf221106.1252
#--


# sources: 
# https://esphome.io/components/sensor/htu21d.html


esphome:
  name: th6

esp8266:
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "th6 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
  level: DEBUG
  logs:
    logger: INFO
    adc: INFO
    captive_portal: INFO
    deep_sleep: INFO
    htu21d: INFO
    i2c: INFO
    ota: INFO
    restart: INFO
    sensor: INFO
    switch: INFO
    switch.gpio: INFO
    uptime.sensor: INFO
    web_server: INFO
    wifi_signal.sensor: INFO
    mqtt: INFO
    mqtt.component: INFO
    mqtt.client: INFO
    mqtt.switch: INFO
    mqtt.sensor: INFO

# Enable Home Assistant API
api:
#  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


# I2C conf
i2c:
  sda: D2
  scl: D1


# Définition des Switch's
switch:
  - platform: gpio
    name: "th6 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "th6 Restart"


# Définition des Sensors
sensor:
  - platform: wifi_signal
    name: "th6 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "th6 uptime"
    update_interval: 60s

  - platform: htu21d
    temperature:
      name: "th6 Température"
    humidity:
      name: "th6 Humidité"
    update_interval: 2s


# Définition des Sensors text
text_sensor:
  - platform: version
    name: "th6 Version 1518"

  - platform: wifi_info
    ip_address:
      name: th6 IP Address
      id: wifi_ip
    ssid:
      name: th6 Connected SSID
      id: wifi_ssid


