#------------------------------
#-- th6.yaml
#-- Petit code mini manilste pour mesurer la température et l'humidité
#-- Lit la tmpérature et l'humidité du capteur HTU21D
#-- location: cave vers interrupteur lumière
#-- zf210720.1023
#--


# sources: 
# https://esphome.io/components/sensor/htu21d.html


esphome:
  name: th6
  platform: ESP8266
  board: nodemcuv2

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "th6 Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Définition des Switch's
switch:
  - platform: gpio
    name: "th6 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "th6 Restart"

# Définition du bouton physique
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "th6 button"
    on_press:
      - switch.toggle: led

# WEB Server
web_server:
  port: 80




# I2C conf
i2c:
  sda: D5
  scl: D6

# Sensors
sensor:
  - platform: wifi_signal
    name: "th6 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "th6 uptime"
    update_interval: 60s

  - platform: htu21d
    temperature:
      name: "th6 Température"
    humidity:
      name: "th6 Humidité"
    update_interval: 15s

