#------------------------------
#-- th7.yaml
#-- Petit code mini manilste pour mesurer la température et l'humidité
#-- Lit la tmpérature et l'humidité du capteur HTU21D
#-- location: salon sur HP basse
#-- zf210720.1023
#--


# sources: 
# https://esphome.io/components/sensor/htu21d.html


esphome:
  name: th7
  platform: ESP8266
  board: nodemcuv2

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "th7 Fallback Hotspot"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
    level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Définition des Switch's
switch:
  - platform: gpio
    name: "th7 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "th7 Restart"

# Définition du bouton physique
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "th7 button"
    on_press:
      - switch.toggle: led

# WEB Server
web_server:
  port: 80




# I2C conf
i2c:
  sda: D5
  scl: D6

# Sensors
sensor:
  - platform: wifi_signal
    name: "th7 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "th7 uptime"
    update_interval: 60s

  - platform: htu21d
    temperature:
      name: "th7 Température"
    humidity:
      name: "th7 Humidité"
    update_interval: 15s

