#------------------------------
#-- th8.yaml
#-- Petit code pour monitorer la température et l'humidité dans une pièce
#-- location: chambre à coucher parents table de nuit zf
#-- zf2300701.1532
#--
# sources: 
# https://esphome.io/components/sensor/htu21d.html

esphome:
  name: th8

esp8266:
  board: d1_mini

# Configuration WIFI
wifi:
  ssid: !secret wifi_ssid_apzuzu7
  password: !secret wifi_pass_apzuzu7

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "th8 Fallback"
    password: !secret ap_wifi_password

captive_portal:

# Enable logging
logger:
  level: DEBUG
  logs:
    logger: INFO
    adc: INFO
    captive_portal: INFO
    deep_sleep: INFO
    htu21d: INFO
    i2c: INFO
    ota: INFO
    restart: INFO
    sensor: INFO
    switch: INFO
    switch.gpio: INFO
    uptime.sensor: INFO
    web_server: INFO
    wifi_signal.sensor: INFO
    mqtt: INFO
    mqtt.component: INFO
    mqtt.client: INFO
    mqtt.switch: INFO
    mqtt.sensor: INFO

# Enable Home Assistant API
api:
#  password: !secret api_password
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# WEB Server
web_server:
  port: 80


# I2C conf
i2c:
  sda: D2
  scl: D1


# Définition des Switch's
switch:
  - platform: gpio
    name: "th8 LED"
    inverted: True
    id: led
    pin: D4

  - platform: restart
    name: "th8 Restart"


# Définition des Sensors
sensor:
  - platform: wifi_signal
    name: "th8 Signal Wi-Fi"
    update_interval: 60s

  - platform: uptime
    name: "th8 uptime"
    update_interval: 60s

  - platform: htu21d
    temperature:
      name: "th8 Température"
    humidity:
      name: "th8 Humidité"
    update_interval: 2s


# Définition des Sensors text
text_sensor:
  - platform: version
    name: "th8 Version 1518"

  - platform: wifi_info
    ip_address:
      name: th8 IP Address
      id: wifi_ip
    ssid:
      name: th8 Connected SSID
      id: wifi_ssid


